/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f303xc.h"
#include "initialise.h"
#include "interrupt.h"
#include "chase_led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	// enable the devices
	enable_clocks();
	initialise_board();

	// choose whether the chase led function is clockwise (c) or anticlockwise (a)
	char direction = 'c';
	int delay = 400000;// 0.4 second before reset

	// set the led chase direction
	led_chase_direction(direction);

	//set the delay time interface with timer
	delay_set(delay);

    /* Loop forever */
	for(;;);
}
